// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: cars/carspb/cars.proto

package carspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Car struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Make  string `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Model string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *Car) Reset() {
	*x = Car{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cars_carspb_cars_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Car) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Car) ProtoMessage() {}

func (x *Car) ProtoReflect() protoreflect.Message {
	mi := &file_cars_carspb_cars_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Car.ProtoReflect.Descriptor instead.
func (*Car) Descriptor() ([]byte, []int) {
	return file_cars_carspb_cars_proto_rawDescGZIP(), []int{0}
}

func (x *Car) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Car) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *Car) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type CarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CarRequest) Reset() {
	*x = CarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cars_carspb_cars_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarRequest) ProtoMessage() {}

func (x *CarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cars_carspb_cars_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarRequest.ProtoReflect.Descriptor instead.
func (*CarRequest) Descriptor() ([]byte, []int) {
	return file_cars_carspb_cars_proto_rawDescGZIP(), []int{1}
}

func (x *CarRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *Car `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CarResponse) Reset() {
	*x = CarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cars_carspb_cars_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarResponse) ProtoMessage() {}

func (x *CarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cars_carspb_cars_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarResponse.ProtoReflect.Descriptor instead.
func (*CarResponse) Descriptor() ([]byte, []int) {
	return file_cars_carspb_cars_proto_rawDescGZIP(), []int{2}
}

func (x *CarResponse) GetResult() *Car {
	if x != nil {
		return x.Result
	}
	return nil
}

type CarWithDeadlineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CarWithDeadlineRequest) Reset() {
	*x = CarWithDeadlineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cars_carspb_cars_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarWithDeadlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarWithDeadlineRequest) ProtoMessage() {}

func (x *CarWithDeadlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cars_carspb_cars_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarWithDeadlineRequest.ProtoReflect.Descriptor instead.
func (*CarWithDeadlineRequest) Descriptor() ([]byte, []int) {
	return file_cars_carspb_cars_proto_rawDescGZIP(), []int{3}
}

func (x *CarWithDeadlineRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CarWithDeadlineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []*Car `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
}

func (x *CarWithDeadlineResponse) Reset() {
	*x = CarWithDeadlineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cars_carspb_cars_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarWithDeadlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarWithDeadlineResponse) ProtoMessage() {}

func (x *CarWithDeadlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cars_carspb_cars_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarWithDeadlineResponse.ProtoReflect.Descriptor instead.
func (*CarWithDeadlineResponse) Descriptor() ([]byte, []int) {
	return file_cars_carspb_cars_proto_rawDescGZIP(), []int{4}
}

func (x *CarWithDeadlineResponse) GetResult() []*Car {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_cars_carspb_cars_proto protoreflect.FileDescriptor

var file_cars_carspb_cars_proto_rawDesc = []byte{
	0x0a, 0x16, 0x63, 0x61, 0x72, 0x73, 0x2f, 0x63, 0x61, 0x72, 0x73, 0x70, 0x62, 0x2f, 0x63, 0x61,
	0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x61, 0x72, 0x73, 0x22, 0x3f,
	0x0a, 0x03, 0x43, 0x61, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x6b, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x6b, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22,
	0x1c, 0x0a, 0x0a, 0x43, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x30, 0x0a,
	0x0b, 0x43, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x63,
	0x61, 0x72, 0x73, 0x2e, 0x43, 0x61, 0x72, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x28, 0x0a, 0x16, 0x43, 0x61, 0x72, 0x57, 0x69, 0x74, 0x68, 0x44, 0x65, 0x61, 0x64, 0x6c, 0x69,
	0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3c, 0x0a, 0x17, 0x43, 0x61, 0x72,
	0x57, 0x69, 0x74, 0x68, 0x44, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x63, 0x61, 0x72, 0x73, 0x2e, 0x43, 0x61, 0x72, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x8c, 0x01, 0x0a, 0x0a, 0x43, 0x61, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x03, 0x43, 0x61, 0x72, 0x12, 0x10, 0x2e,
	0x63, 0x61, 0x72, 0x73, 0x2e, 0x43, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x11, 0x2e, 0x63, 0x61, 0x72, 0x73, 0x2e, 0x43, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0f, 0x43, 0x61, 0x72, 0x57, 0x69, 0x74, 0x68, 0x44,
	0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x1c, 0x2e, 0x63, 0x61, 0x72, 0x73, 0x2e, 0x43,
	0x61, 0x72, 0x57, 0x69, 0x74, 0x68, 0x44, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x61, 0x72, 0x73, 0x2e, 0x43, 0x61, 0x72,
	0x57, 0x69, 0x74, 0x68, 0x44, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x63, 0x61, 0x72, 0x73, 0x2f, 0x63,
	0x61, 0x72, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cars_carspb_cars_proto_rawDescOnce sync.Once
	file_cars_carspb_cars_proto_rawDescData = file_cars_carspb_cars_proto_rawDesc
)

func file_cars_carspb_cars_proto_rawDescGZIP() []byte {
	file_cars_carspb_cars_proto_rawDescOnce.Do(func() {
		file_cars_carspb_cars_proto_rawDescData = protoimpl.X.CompressGZIP(file_cars_carspb_cars_proto_rawDescData)
	})
	return file_cars_carspb_cars_proto_rawDescData
}

var file_cars_carspb_cars_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_cars_carspb_cars_proto_goTypes = []interface{}{
	(*Car)(nil),                     // 0: cars.Car
	(*CarRequest)(nil),              // 1: cars.CarRequest
	(*CarResponse)(nil),             // 2: cars.CarResponse
	(*CarWithDeadlineRequest)(nil),  // 3: cars.CarWithDeadlineRequest
	(*CarWithDeadlineResponse)(nil), // 4: cars.CarWithDeadlineResponse
}
var file_cars_carspb_cars_proto_depIdxs = []int32{
	0, // 0: cars.CarResponse.result:type_name -> cars.Car
	0, // 1: cars.CarWithDeadlineResponse.result:type_name -> cars.Car
	1, // 2: cars.CarService.Car:input_type -> cars.CarRequest
	3, // 3: cars.CarService.CarWithDeadline:input_type -> cars.CarWithDeadlineRequest
	2, // 4: cars.CarService.Car:output_type -> cars.CarResponse
	4, // 5: cars.CarService.CarWithDeadline:output_type -> cars.CarWithDeadlineResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cars_carspb_cars_proto_init() }
func file_cars_carspb_cars_proto_init() {
	if File_cars_carspb_cars_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cars_carspb_cars_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Car); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cars_carspb_cars_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cars_carspb_cars_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cars_carspb_cars_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarWithDeadlineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cars_carspb_cars_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarWithDeadlineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cars_carspb_cars_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cars_carspb_cars_proto_goTypes,
		DependencyIndexes: file_cars_carspb_cars_proto_depIdxs,
		MessageInfos:      file_cars_carspb_cars_proto_msgTypes,
	}.Build()
	File_cars_carspb_cars_proto = out.File
	file_cars_carspb_cars_proto_rawDesc = nil
	file_cars_carspb_cars_proto_goTypes = nil
	file_cars_carspb_cars_proto_depIdxs = nil
}
